### PR TITLE
skipjack,swift: Fix WLAN

### LINKED ISSUE #188: Enable WLAN support.
`swift` theoretically has support for WiFi functionality.
But we need to enable this in the platform configuration and provide the wifi enabler service or use `sys.boot_completed`.

### LINKED ISSUE #208: [skipjack]  WiFi needs a patch to run
With this issue, I'd like to revive this 2021 pull request: https://github.com/AsteroidOS/meta-skipjack-hybris/pull/12

Although the suggestion in reply to that PR was to instead move the things done in that service file to `/etc/init.rc` the current kernel version in use does not have or use that file.

### PR DESCRIPTION
**Pull request by MagneFire**
Depends on: https://github.com/AsteroidOS/meta-asteroid/pull/173

This fixes #188 and fixes #208.

### CODE REVIEW

**Comment by MagneFire** [comment]
Good point!

**Comment by MagneFire** [comment]
I've updated the system tarball and updated init.rc. Can you check again if it works now?

**Comment by beroset** [comment]
It boots and I can scan for and see my local WiFi network, but it does not connect.  I get this:
```
Agent ReportError wifi_9828a6ecb48a_6768657a7a695f6775657374_managed_psk
  connect-failed
Agent request cancelled by ConnMan
Error /net/connman/service/wifi_9828a6ecb48a_6768657a7a695f6775657374_managed_psk: Input/output error
```
I'm investigating.

**Comment by beroset** [comment]
System log contains this:
```
Aug 04 13:38:23 skipjack wpa_supplicant[678]: p2p0: Failed to initiate sched scan
Aug 04 13:38:23 skipjack kernel: [13:38:23.668664] [0000000532099A6E] [VosMC]  wlan: [E :HDD] wlan_hdd_tdls_scan_done_callback: 3073: Failed to revert: Mode=0, BTC enabled=1
Aug 04 13:38:23 skipjack kernel: [13:38:23.672752] [00000005320ACD02] [wpa_s]  wlan: [E :HDD] __wlan_hdd_cfg80211_sched_scan_start: Network input is not correct 0 Max Network supported is 16
Aug 04 13:38:24 skipjack wpa_supplicant[678]: wlan0: Failed to initiate sched scan
Aug 04 13:38:24 skipjack kernel: [13:38:24.058340] [00000005327BC415] [VosMC]  wlan: [E :HDD] wlan_hdd_tdls_scan_done_callback: 3073: Failed to revert: Mode=0, BTC enabled=1
Aug 04 13:38:24 skipjack kernel: [13:38:24.060451] [00000005327C6267] [wpa_s]  wlan: [E :HDD] __wlan_hdd_cfg80211_sched_scan_start: Network input is not correct 0 Max Network supported is 16
Aug 04 13:38:24 skipjack kernel: send_filled_buffers_to_user: 47 callbacks suppressed
Aug 04 13:38:24 skipjack kernel: send_filled_buffers_to_user: Send Failed -3 drop_count = 2954
Aug 04 13:38:29 skipjack kernel: ether_ioctl: [rndis0] error: ioctl called for unsupported cmd[35591]
Aug 04 13:38:29 skipjack kernel: ether_ioctl: [rndis0] error: ioctl called for unsupported cmd[35591]
Aug 04 13:38:29 skipjack kernel: send_filled_buffers_to_user: 9 callbacks suppressed
Aug 04 13:38:29 skipjack kernel: send_filled_buffers_to_user: Send Failed -3 drop_count = 2964
Aug 04 13:38:29 skipjack wpa_supplicant[678]: p2p0: Failed to initiate sched scan
```

**Comment by MagneFire** [comment]
> System log contains this:
> 
> ```
> Aug 04 13:38:23 skipjack wpa_supplicant[678]: p2p0: Failed to initiate sched scan
> Aug 04 13:38:23 skipjack kernel: [13:38:23.668664] [0000000532099A6E] [VosMC]  wlan: [E :HDD] wlan_hdd_tdls_scan_done_callback: 3073: Failed to revert: Mode=0, BTC enabled=1
> Aug 04 13:38:23 skipjack kernel: [13:38:23.672752] [00000005320ACD02] [wpa_s]  wlan: [E :HDD] __wlan_hdd_cfg80211_sched_scan_start: Network input is not correct 0 Max Network supported is 16
> Aug 04 13:38:24 skipjack wpa_supplicant[678]: wlan0: Failed to initiate sched scan
> Aug 04 13:38:24 skipjack kernel: [13:38:24.058340] [00000005327BC415] [VosMC]  wlan: [E :HDD] wlan_hdd_tdls_scan_done_callback: 3073: Failed to revert: Mode=0, BTC enabled=1
> Aug 04 13:38:24 skipjack kernel: [13:38:24.060451] [00000005327C6267] [wpa_s]  wlan: [E :HDD] __wlan_hdd_cfg80211_sched_scan_start: Network input is not correct 0 Max Network supported is 16
> Aug 04 13:38:24 skipjack kernel: send_filled_buffers_to_user: 47 callbacks suppressed
> Aug 04 13:38:24 skipjack kernel: send_filled_buffers_to_user: Send Failed -3 drop_count = 2954
> Aug 04 13:38:29 skipjack kernel: ether_ioctl: [rndis0] error: ioctl called for unsupported cmd[35591]
> Aug 04 13:38:29 skipjack kernel: ether_ioctl: [rndis0] error: ioctl called for unsupported cmd[35591]
> Aug 04 13:38:29 skipjack kernel: send_filled_buffers_to_user: 9 callbacks suppressed
> Aug 04 13:38:29 skipjack kernel: send_filled_buffers_to_user: Send Failed -3 drop_count = 2964
> Aug 04 13:38:29 skipjack wpa_supplicant[678]: p2p0: Failed to initiate sched scan
> ```

I'm getting similar errors on `swift` and `ray`. But that still allows me to connect to an access point. I did notice duplicate entries though, one would connect while the other would not.

**Comment by beroset** [comment]
Also got duplicate entries here, but they have the same number.  Example:
```
    HLComfort_Guest      wifi_9828a6ecb48a_484c436f6d666f72745f4775657374_managed_psk
    HLComfort_Guest      wifi_9a28a6ecb48a_484c436f6d666f72745f4775657374_managed_psk
    ATT4GZZ8el           wifi_9a28a6ecb48a_41545434475a5a38656c_managed_psk
    ATT4GZZ8el           wifi_9828a6ecb48a_41545434475a5a38656c_managed_psk
    HLComfort            wifi_9a28a6ecb48a_484c436f6d666f7274_managed_psk
    HLComfort            wifi_9828a6ecb48a_484c436f6d666f7274_managed_psk
```

**Comment by MagneFire** [comment]
There's a one character difference between them `9a` vs `98`. But does connecting to both of them result in a connection failure?

**Comment by beroset** [comment]
I just reset my WiFi AP and now it connects!  Tested using `asteroid-weatherfetch` and it works just fine now.

**Review by beroset — APPROVED** [review]
Looks clean and has been successfully tested on `skipjack`.

**Review by FlorentRevest — APPROVED** [review]

**Pull request merged**
